services:
  api-cpu:
    profiles: ["cpu"]
    build:
      context: .
      dockerfile: Dockerfile.cpu
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  api-gpu:
    profiles: ["gpu"]
    build:
      context: .
      dockerfile: Dockerfile.gpu
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
