"""initial tables

Revision ID: 7d6417c70acb
Revises: 
Create Date: 2025-12-21 22:40:14.346771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d6417c70acb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_incident_management',
    sa.Column('phone_hash', sa.String(), nullable=False),
    sa.Column('report_count', sa.Integer(), nullable=True),
    sa.Column('last_reported_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_banned', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('phone_hash')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone_hash', sa.String(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('device_model', sa.String(length=50), nullable=True),
    sa.Column('app_version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default='now()', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recordings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default='now()', nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('report_category', sa.String(length=50), nullable=True),
    sa.Column('reported_at', sa.TIMESTAMP(), server_default='now()', nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analysis_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('recording_id', sa.UUID(), nullable=True),
    sa.Column('phishing_risk_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('deepvoice_risk_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('final_decision', sa.String(length=20), nullable=True),
    sa.Column('threshold', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('analyzed_at', sa.TIMESTAMP(), server_default='now()', nullable=True),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chunk_analysis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('recording_id', sa.UUID(), nullable=True),
    sa.Column('analysis_result_id', sa.UUID(), nullable=True),
    sa.Column('stt_text', sa.Text(), nullable=False),
    sa.Column('chunk_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default='now()', nullable=True),
    sa.ForeignKeyConstraint(['analysis_result_id'], ['analysis_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('analysis_result_id', sa.UUID(), nullable=True),
    sa.Column('report_type', sa.String(length=30), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('action_guide', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default='now()', nullable=True),
    sa.ForeignKeyConstraint(['analysis_result_id'], ['analysis_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_reports')
    op.drop_table('chunk_analysis')
    op.drop_table('analysis_results')
    op.drop_table('reports')
    op.drop_table('recordings')
    op.drop_table('users')
    op.drop_table('post_incident_management')
    # ### end Alembic commands ###
